name: Run Postman Collection with Newman

on:
  schedule:
    - cron: '30 1 * * *'  # 22:30 hora Argentina
    - cron: '45 1 * * *'  # 22:45 hora Argentina
  push:
    branches: [main]  # Cambiá si usás otra rama
  pull_request:

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run postman/Alert.postman_collection.json \
            --reporters cli,json \
            --reporter-json-export newman-report.json
